# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5876cb29cb274916d79ed3ae5fa94d83631e56398598a64e2d3be3ea6f2d05860fcb23b841c34ae095287d1f6010080cfb1433aff0784dbc04c49490959e71dd

test:
  secret_key_base: c44c5cc1a6b2f5b9b50695b87d3f435137e07755ece7b8ee30c5c4066e8ac76d99417c82e51a38b0a28d5fa1833d6e39e9c7638d0ffcf4c4f88ff36b1cb35758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
